name: Java CI with Maven

on:
  push:
    branches: [ "master", "feature/**" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Grant execute permission for mvnw
      run: chmod +x mvnw
    
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: ./mvnw clean install -Dmaven.javadoc.failOnError=false -Dmaven.javadoc.skip=false -Dmaven.test.skip=false

    - name: Run tests and generate coverage report
      run: ./mvnw test org.jacoco:jacoco-maven-plugin:report

    # 上传测试报告（如果需要的话）
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: false
        verbose: true